### PR TITLE
Change RecyclableMemoryStreamManager.GetStream to return RecyclableMemoryStream

### LINKED ISSUE #165: RecylableMemoryStreamManager.GetStream should return RMS instead of MS
Verify binary compatibility is maintained.

### PR DESCRIPTION
**Pull request by lechu445**
resolves #165

### CODE REVIEW

**Comment by benmwatson** [comment]
This will be held for 3.0 (hoping to get the infrastructure in place for this soon-ish...lots of competing things right now).

We will likely be removing some of the GetStream overloads to simplify the API surface area a little bit, but it likely doesn't matter if it comes before or after this change.

**Comment by benmwatson** [comment]
@lechu445 Please take a look at the conflicts and I'll review this soon.

**Comment by lechu445** [comment]
@benmwatson done

**Comment by lechu445** [comment]
@benmwatson I resolved conflicts once again

**Review by grbell-ms — APPROVED** [review]

**Review by benmwatson — APPROVED** [review]

**Pull request merged**
