### PR TITLE
Support for .NET 5

### PR DESCRIPTION
**Pull request by jochenjonc**
Added net5.0 as TargetFramework

### CODE REVIEW

**Comment by benmwatson** [comment]
I would rather not add a new target unless it is taking advantage of features present in that version. There is nothing to be gained by adding net5.0 at this time. 

I could see changing the rollForward value in global.json to build against later frameworks if you don't have 3.x installed.

**Comment by jochenjonc** [comment]
Ok, I understand. But then maybe netcoreapp2.1 should also be removed.

**Comment by DenSmoke** [comment]
I think adding net5 TFM is good for future improvements. I mean you can't add features from net5 without targeting to it.

**Comment by benmwatson** [comment]
@DenSmoke If we add a feature that relies on net5, then we'll definitely need to add it then, but now, it's just not accurate. There are not net5-specific features.

@jochenjonc Both netstandard2.1 and netcoreapp2.1 are needed because they are targeting different things. netstandard2.1 is implemented by .NET Core 3.0, but there are features that .NET Core 2.1 supports, which aren't in netstandard2.0, hence the seeming duplication there. It's unfortunate, and a little messy.

I am actually considering dropping support for net40 soon, but it depends on how many more things are implemented that won't be supported back that far. I'd like the library to remain very flexible and able to be used under very different situations.

**Comment by benmwatson** [comment]
Closing this because the library supports net5 as-is and there are no net5-specific methods yet.

**Pull request closed without merging**
