### PR TITLE
Allocate buffers using GC.AllocateUninitializedArray on .NET 5

### PR DESCRIPTION
**Pull request by grbell-ms**
[GC.AllocateUninitializedArray](https://docs.microsoft.com/en-us/dotnet/api/system.gc.allocateuninitializedarray) is a new API in .NET 5 that does not guarantee that the array it returns is zero-initialized. This can significantly speed up large allocations such as the buffers used by RecyclableMemoryStream. How much faster? On my machine, unit test time went from 63s to 52s (not including the speed improvements from upgrading to .NET 5).

This is a *slight* behavioral change. Streams that are allocated before any other streams are disposed are no longer guaranteed to be zero-initialized. In rare cases this may break user code, but I don't think it's worth preserving compatibility.

### CODE REVIEW

**Review by paulomorgado — COMMENTED** [review]
I think this should be a setting on the manager. And, maybe, it's time to move to a settings class as a parameter to avoid an explosion of overloads.

One of the reasons objects are initialized to 0 is for security reasons. An object won't get the data from previous objects.

Come to think of that, this should be a setting for segments being returned, also.

**Comment by grbell-ms** [comment]
@paulomorgado A setting to control zeroing buffers is a good idea (for another PR). However, I think not zeroing is a good default: 

- The usual ways of using a stream do not expose the uninitialized memory
- Users can conditionally zero memory when needed
- There is a high performance cost to zeroing

`ArrayPool<byte>.Default` makes a similar choice. It always allocates using `GC.AllocateUninitializedArray` and by default does not clear returned arrays.

---

If we make an options class, we could wire this library up for the [options pattern](https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors). Just add a constructor to the manager that takes an `IOptions<RMSOptions>` parameter, create an `AddRecyclableMemoryStreamManager()` extension method for `IServiceCollection`, and suddenly it's easy to share an instance of RMSManager across an entire application.

**Comment by benmwatson** [comment]
RMS was designed as a drop-in replacement of MemoryStream, so zero-initialized arrays would match that behavior. That said, we are slowly moving away from a perfect replacement. There is a lot more functionality now. I think it's a matter of which should be the default. My preference is the default should be the classic behavior, with an option to avoid zeroing buffers.

**Comment by grbell-ms** [comment]
But RMS already provides non-initialized arrays by default. Pooled buffers are cleared neither when returned not when rented.

**Comment by benmwatson** [comment]
Ah yes, you're right...I had a brain fart. I even remember explicitly making this decision early on for performance reasons...

**Comment by paulomorgado** [comment]
This whole thing prompted me to think about it.

We should provide a safe replacement. There might be reasons for the user to want a zeroed buffer. Not only when allocating, but also when releasing.

A user might be expecting that the stream is a drop-in replacement for `MemoryStream` and that should be possible and still yield benefits.

But, as @grbell-ms, said, the PR has net benefits, and it doesn't make it any "worst".

We should do separate issues/PRs for using a settings class (or struct) to not explode the number of constructors and another to have configurations for zeroing the buffers on acquire and/or release.

**Comment by Cricle** [comment]
捕获


I think use `ArrayPool` is better than use `AllocateUninitializedArray`. The image is benchmark result. Alloc 0, 10, 100, 256, 1024 size array.

**Comment by paulomorgado** [comment]
@Cricle, can you share the benchmark code and the results as text?

**Comment by Cricle** [comment]
@paulomorgado 

## The result

``` ini

BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19042.985 (20H2/October2020Update)
Intel Core i5-7200U CPU 2.50GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
.NET SDK=6.0.100-preview.4.21255.9
  [Host]     : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT
  DefaultJob : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT


```
|                     Method | Count |         Mean |       Error |      StdDev |       Median | Ratio | RatioSD |  Gen 0 |  Gen 1 |  Gen 2 | Allocated |
|--------------------------- |------ |-------------:|------------:|------------:|-------------:|------:|--------:|-------:|-------:|-------:|----------:|
|                **NormalAlloc** |     **0** |     **4.975 ns** |   **0.5771 ns** |   **1.7015 ns** |     **4.175 ns** |  **1.00** |    **0.00** | **0.0153** |      **-** |      **-** |      **24 B** |
| AllocateUninitializedArray |     0 |   153.505 ns |   3.0912 ns |   5.8812 ns |   152.169 ns | 25.92 |    7.21 | 0.0074 | 0.0074 | 0.0074 |      24 B |
|              AllocateArray |     0 |   155.987 ns |   3.2870 ns |   9.2711 ns |   152.203 ns | 34.26 |    9.21 | 0.0074 | 0.0074 | 0.0074 |      24 B |
|                  ArrayPool |     0 |     9.425 ns |   0.2079 ns |   0.1945 ns |     9.358 ns |  1.56 |    0.39 |      - |      - |      - |         - |
|                            |       |              |             |             |              |       |         |        |        |        |           |
|                **NormalAlloc** |    **10** |    **13.589 ns** |   **0.2811 ns** |   **0.2630 ns** |    **13.533 ns** |  **1.00** |    **0.00** | **0.0408** |      **-** |      **-** |      **64 B** |
| AllocateUninitializedArray |    10 |   182.521 ns |   2.1786 ns |   1.8192 ns |   182.782 ns | 13.42 |    0.25 | 0.0203 | 0.0203 | 0.0203 |      64 B |
|              AllocateArray |    10 |   181.470 ns |   2.8207 ns |   2.3554 ns |   181.954 ns | 13.34 |    0.39 | 0.0203 | 0.0203 | 0.0203 |      64 B |
|                  ArrayPool |    10 |    42.919 ns |   0.8966 ns |   0.9207 ns |    42.721 ns |  3.16 |    0.09 |      - |      - |      - |         - |
|                            |       |              |             |             |              |       |         |        |        |        |           |
|                **NormalAlloc** |   **100** |   **103.304 ns** |   **1.9796 ns** |   **1.8517 ns** |   **102.674 ns** |  **1.00** |    **0.00** | **0.2702** |      **-** |      **-** |     **424 B** |
| AllocateUninitializedArray |   100 |   532.721 ns |   7.2795 ns |   6.8093 ns |   531.699 ns |  5.16 |    0.13 | 0.1345 | 0.1345 | 0.1345 |     424 B |
|              AllocateArray |   100 |   515.446 ns |   9.8486 ns |   8.7305 ns |   513.823 ns |  4.99 |    0.11 | 0.1345 | 0.1345 | 0.1345 |     424 B |
|                  ArrayPool |   100 |   163.970 ns |   1.7331 ns |   1.4472 ns |   163.940 ns |  1.59 |    0.03 |      - |      - |      - |         - |
|                            |       |              |             |             |              |       |         |        |        |        |           |
|                **NormalAlloc** |   **256** |   **211.241 ns** |   **4.2539 ns** |   **6.3670 ns** |   **210.928 ns** |  **1.00** |    **0.00** | **0.6678** |      **-** |      **-** |   **1,048 B** |
| AllocateUninitializedArray |   256 | 1,160.490 ns |  28.8503 ns |  80.4231 ns | 1,151.162 ns |  5.31 |    0.38 | 0.3319 | 0.3319 | 0.3319 |   1,048 B |
|              AllocateArray |   256 | 1,160.105 ns |  40.3901 ns | 113.2581 ns | 1,124.329 ns |  5.29 |    0.35 | 0.3319 | 0.3319 | 0.3319 |   1,048 B |
|                  ArrayPool |   256 |   300.758 ns |   5.0090 ns |   4.4404 ns |   301.092 ns |  1.42 |    0.06 |      - |      - |      - |         - |
|                            |       |              |             |             |              |       |         |        |        |        |           |
|                **NormalAlloc** |  **1024** |   **829.232 ns** |  **16.1394 ns** |  **38.3571 ns** |   **820.999 ns** |  **1.00** |    **0.00** | **2.6245** |      **-** |      **-** |   **4,120 B** |
| AllocateUninitializedArray |  1024 | 4,358.532 ns | 199.8964 ns | 589.3991 ns | 4,491.877 ns |  5.01 |    0.66 | 1.3046 | 1.3046 | 1.3046 |   4,120 B |
|              AllocateArray |  1024 | 4,841.311 ns |  94.6349 ns | 177.7473 ns | 4,872.293 ns |  5.85 |    0.31 | 1.3046 | 1.3046 | 1.3046 |   4,120 B |
|                  ArrayPool |  1024 | 1,429.629 ns |  28.1307 ns |  34.5471 ns | 1,433.945 ns |  1.74 |    0.08 |      - |      - |      - |         - |


## The code

```csharp
    [MemoryDiagnoser]
    public class Benchmarks
    {
    [Params(0, 10, 100, 256, 1024)]
    public int Count { get; set; }
    
    [Benchmark(Baseline = true)]
    public void NormalAlloc()
    {
        var i = 0;
        var buffer= new int[Count];
        foreach (var item in buffer)
        {
            i += item;
        }
    }
    [Benchmark]
    public void AllocateUninitializedArray()
    {
        var i = 0;
        var buffer = GC.AllocateUninitializedArray<int>(Count, true);
        foreach (var item in buffer)
        {
            i += item;
        }
    }
    [Benchmark]
    public void AllocateArray()
    {
        var i = 0;
        var buffer = GC.AllocateArray<int>(Count, true);
        foreach (var item in buffer)
        {
            i += item;
        }
    }
    [Benchmark]
    public void ArrayPool()
    {
        var i = 0;
        var buffer = ArrayPool<int>.Shared.Rent(Count);
        foreach (var item in buffer)
        {
            i += item;
        }
    
        ArrayPool<int>.Shared.Return(buffer);
    }
```

Element accumulation is to make the function execution time not so short.

[AllocArray.zip](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/files/6568436/AllocArray.zip)
[results.zip](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/files/6568516/results.zip)

**Comment by paulomorgado** [comment]
I don't think comparing an array pool with the way an array is obtained for a pool is a fair comparison.

I reduced the measurement to the actual allocation of the array and dropped the 0-length array. No one should be allocating a 0-length array.

```CSharp
[MemoryDiagnoser]
public class Benchmark
{
    public IEnumerable<int> Data()
    {
        yield return 1;
        yield return 1024;
        yield return 32 * 1024;
        yield return 64 * 1024;
        yield return 128 * 1024;
        yield return 1024 * 1024;
    }

    [Benchmark(Baseline = true)]
    [ArgumentsSource(nameof(Data))]
    public byte[] ArrayAllocation(int size) => new byte[size];

    [Benchmark()]
    [ArgumentsSource(nameof(Data))]
    public byte[] GC_AllocateUninitializedArray(int size) => GC.AllocateUninitializedArray<byte>(size);

    [Benchmark()]
    [ArgumentsSource(nameof(Data))]
    public byte[] GC_AllocateArray(int size) => GC.AllocateArray<byte>(size);
}
```

BenchmarkDotNet=v0.13.0, OS=Windows 10.0.21390
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100-preview.4.21255.9
  [Host]     : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT
  DefaultJob : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT


|                        Method |    size |          Mean |         Error |         StdDev |        Median | Ratio | RatioSD |   Gen 0 |   Gen 1 |   Gen 2 |   Allocated |
|------------------------------ |-------- |--------------:|--------------:|---------------:|--------------:|------:|--------:|--------:|--------:|--------:|------------:|
|               ArrayAllocation |       1 |      5.173 ns |     0.1937 ns |      0.4086 ns |      5.149 ns |  1.00 |    0.00 |  0.0076 |       - |       - |        32 B |
| GC_AllocateUninitializedArray |       1 |      7.515 ns |     0.8662 ns |      2.4712 ns |      6.327 ns |  1.26 |    0.32 |  0.0076 |       - |       - |        32 B |
|              GC_AllocateArray |       1 |     36.110 ns |     0.8076 ns |      1.5169 ns |     35.988 ns |  7.05 |    0.69 |  0.0076 |       - |       - |        32 B |
|                               |         |               |               |                |               |       |         |         |         |         |             |
|               ArrayAllocation |    1024 |     64.865 ns |     2.6310 ns |      7.2906 ns |     62.374 ns |  1.00 |    0.00 |  0.2505 |       - |       - |     1,048 B |
| GC_AllocateUninitializedArray |    1024 |     93.893 ns |     7.1933 ns |     20.9831 ns |     90.561 ns |  1.50 |    0.33 |  0.2505 |       - |       - |     1,048 B |
|              GC_AllocateArray |    1024 |    117.434 ns |     4.2684 ns |     12.3833 ns |    116.588 ns |  1.82 |    0.23 |  0.2505 |       - |       - |     1,048 B |
|                               |         |               |               |                |               |       |         |         |         |         |             |
|               ArrayAllocation |   32768 |  1,743.281 ns |    56.6939 ns |    162.6654 ns |  1,692.601 ns |  1.00 |    0.00 |  7.8106 |  0.0019 |       - |    32,792 B |
| GC_AllocateUninitializedArray |   32768 |    438.476 ns |     9.1042 ns |     26.4130 ns |    433.084 ns |  0.25 |    0.03 |  7.8115 |  0.0010 |       - |    32,792 B |
|              GC_AllocateArray |   32768 |  1,931.883 ns |    71.3756 ns |    196.5890 ns |  1,886.754 ns |  1.13 |    0.15 |  7.8087 |  0.0038 |       - |    32,792 B |
|                               |         |               |               |                |               |       |         |         |         |         |             |
|               ArrayAllocation |   65536 |  3,492.020 ns |   159.3790 ns |    449.5312 ns |  3,410.239 ns |  1.00 |    0.00 | 15.6174 |  0.0076 |       - |    65,560 B |
| GC_AllocateUninitializedArray |   65536 |    831.104 ns |    16.2386 ns |     37.9572 ns |    826.274 ns |  0.24 |    0.03 | 15.6240 |  0.0010 |       - |    65,560 B |
|              GC_AllocateArray |   65536 |  3,162.935 ns |    84.9808 ns |    241.0763 ns |  3,090.569 ns |  0.92 |    0.13 | 15.6212 |  0.0038 |       - |    65,560 B |
|                               |         |               |               |                |               |       |         |         |         |         |             |
|               ArrayAllocation |  131072 |  9,893.179 ns |   240.5907 ns |    682.5156 ns |  9,776.544 ns |  1.00 |    0.00 | 41.6565 | 41.6565 | 41.6565 |   131,096 B |
| GC_AllocateUninitializedArray |  131072 |  5,099.401 ns |   102.0573 ns |    203.8194 ns |  5,054.722 ns |  0.52 |    0.04 | 41.6641 | 41.6641 | 41.6641 |   131,096 B |
|              GC_AllocateArray |  131072 | 11,080.794 ns |   491.9364 ns |  1,442.7644 ns | 10,964.820 ns |  1.13 |    0.15 | 41.6565 | 41.6565 | 41.6565 |   131,096 B |
|                               |         |               |               |                |               |       |         |         |         |         |             |
|               ArrayAllocation | 1048576 | 52,098.620 ns | 1,422.1172 ns |  4,034.3097 ns | 51,741.205 ns |  1.00 |    0.00 | 41.1377 | 41.1377 | 41.1377 | 1,048,593 B |
| GC_AllocateUninitializedArray | 1048576 | 19,152.348 ns | 1,382.0080 ns |  4,074.8817 ns | 18,179.555 ns |  0.37 |    0.09 |  5.5847 |  5.5847 |  5.5847 | 1,048,595 B |
|              GC_AllocateArray | 1048576 | 56,158.986 ns | 2,535.1246 ns |  7,191.7266 ns | 54,945.374 ns |  1.08 |    0.15 | 38.6963 | 38.6963 | 38.6963 | 1,048,595 B |

**Comment by Cricle** [comment]
Thank you for pointing out the mistake.

I did write the benchmark test wrong, in my machine, i got this result.

``` ini

BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19042.985 (20H2/October2020Update)
Intel Core i5-7200U CPU 2.50GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
.NET SDK=6.0.100-preview.4.21255.9
  [Host]     : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT
  DefaultJob : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT


```
|                        Method |    size |           Mean |          Error |         StdDev |         Median | Ratio | RatioSD |   Gen 0 |   Gen 1 |   Gen 2 |   Allocated |
|------------------------------ |-------- |---------------:|---------------:|---------------:|---------------:|------:|--------:|--------:|--------:|--------:|------------:|
|               **ArrayAllocation** |       **1** |       **4.172 ns** |      **0.4357 ns** |      **1.2570 ns** |       **3.562 ns** |  **1.00** |    **0.00** |  **0.0204** |       **-** |       **-** |        **32 B** |
| GC_AllocateUninitializedArray |       1 |       5.069 ns |      0.2972 ns |      0.8432 ns |       4.721 ns |  1.33 |    0.40 |  0.0204 |       - |       - |        32 B |
|              GC_AllocateArray |       1 |      32.442 ns |      0.8521 ns |      2.4855 ns |      31.081 ns |  8.41 |    2.29 |  0.0204 |       - |       - |        32 B |
|                               |         |                |                |                |                |       |         |         |         |         |             |
|               **ArrayAllocation** |    **1024** |      **61.769 ns** |      **0.8041 ns** |      **0.7128 ns** |      **61.801 ns** |  **1.00** |    **0.00** |  **0.6679** |       **-** |       **-** |     **1,048 B** |
| GC_AllocateUninitializedArray |    1024 |      64.577 ns |      1.2232 ns |      1.8680 ns |      64.075 ns |  1.06 |    0.05 |  0.6679 |       - |       - |     1,048 B |
|              GC_AllocateArray |    1024 |      91.465 ns |      1.8824 ns |      1.7608 ns |      92.329 ns |  1.48 |    0.03 |  0.6679 |       - |       - |     1,048 B |
|                               |         |                |                |                |                |       |         |         |         |         |             |
|               **ArrayAllocation** |   **32768** |   **1,754.935 ns** |     **27.7154 ns** |     **24.5690 ns** |   **1,760.560 ns** |  **1.00** |    **0.00** | **20.8321** |       **-** |       **-** |    **32,792 B** |
| GC_AllocateUninitializedArray |   32768 |     909.515 ns |     20.3063 ns |     58.5884 ns |     885.921 ns |  0.51 |    0.03 | 20.8330 |       - |       - |    32,792 B |
|              GC_AllocateArray |   32768 |   1,864.983 ns |     37.0091 ns |     96.1915 ns |   1,822.888 ns |  1.12 |    0.05 | 20.8321 |       - |       - |    32,792 B |
|                               |         |                |                |                |                |       |         |         |         |         |             |
|               **ArrayAllocation** |   **65536** |   **3,691.688 ns** |     **71.0922 ns** |     **76.0679 ns** |   **3,684.850 ns** |  **1.00** |    **0.00** | **41.6641** |       **-** |       **-** |    **65,560 B** |
| GC_AllocateUninitializedArray |   65536 |   1,863.518 ns |     41.5117 ns |    119.7709 ns |   1,813.933 ns |  0.52 |    0.03 | 41.6660 |       - |       - |    65,560 B |
|              GC_AllocateArray |   65536 |   3,866.762 ns |    125.1907 ns |    348.9817 ns |   3,793.149 ns |  1.03 |    0.07 | 41.6641 |       - |       - |    65,560 B |
|                               |         |                |                |                |                |       |         |         |         |         |             |
|               **ArrayAllocation** |  **131072** |  **12,393.866 ns** |    **442.4100 ns** |  **1,283.5117 ns** |  **12,266.550 ns** |  **1.00** |    **0.00** | **41.6565** | **41.6565** | **41.6565** |   **131,096 B** |
| GC_AllocateUninitializedArray |  131072 |   4,837.614 ns |     96.4053 ns |    273.4858 ns |   4,755.228 ns |  0.39 |    0.04 | 41.6641 | 41.6641 | 41.6641 |   131,096 B |
|              GC_AllocateArray |  131072 |  11,368.753 ns |    214.5875 ns |    293.7297 ns |  11,273.348 ns |  0.93 |    0.10 | 41.6565 | 41.6565 | 41.6565 |   131,096 B |
|                               |         |                |                |                |                |       |         |         |         |         |             |
|               **ArrayAllocation** | **1048576** | **303,636.412 ns** | **10,893.4915 ns** | **31,948.7249 ns** | **311,600.037 ns** |  **1.00** |    **0.00** | **48.3398** | **48.3398** | **48.3398** | **1,048,594 B** |
| GC_AllocateUninitializedArray | 1048576 |  24,546.219 ns |  2,874.8365 ns |  8,476.5202 ns |  23,075.937 ns |  0.08 |    0.03 |  6.2866 |  6.2866 |  6.2866 | 1,048,594 B |
|              GC_AllocateArray | 1048576 | 316,875.506 ns | 11,333.3348 ns | 33,416.5933 ns | 324,822.095 ns |  1.06 |    0.17 | 43.4570 | 43.4570 | 43.4570 | 1,048,594 B |

**Review by paulomorgado — APPROVED** [review]

**Review by benmwatson — APPROVED** [review]

**Pull request merged**
